services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Plavi.12.
      - MSSQL_DATABASE=EmailDB
    ports:
      - "1433:1433"
    networks:
      - sql_network
    volumes:
      - sql_data:/var/opt/mssql
  
  webapi:
    build:
      context: . 
      dockerfile: WebApi/Dockerfile
    container_name: web_api_container
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EmailDB;User Id=SA;Password=Plavi.12.;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - sql_network
  
  angular-app:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge

volumes:
  sql_data:
